name: Main CI Bank Prediction

on:
  push:
    branches: [ "master" ] # Le déclencheur (Trigger) [cite: 22, 23, 31]

jobs:
  # Job 1 : Analyse statique (Linting) [cite: 33]
  lint-python:
    runs-on: ubuntu-latest # Le Runner [cite: 18, 36]
    steps:
      - uses: actions/checkout@v4 # Étape 1 : Récupérer le code [cite: 38]
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install flake8
        run: pip install flake8

      - name: Lint with flake8
        # Scanne le dossier code/ pour les erreurs de syntaxe [cite: 46, 47]
        run: |
          flake8 backend_app/ --count --select=E9,F63,F7,F82 --show-source --statistics

  # Job 2 : Vérification de l'intégrité Docker [cite: 49]
  build-docker-backend:
    needs: lint-python # Stratégie "Fail-Fast" : dépend du succès du linting [cite: 53, 62, 63]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Docker Image
        # Construit l'image à partir du Dockerfile.backend [cite: 61]
        run: docker build -t bank-prediction-backend:latest -f Dockerfile.backend .